### ISSUE TITLE
one try

### ISSUE THREAD

**Issue by laopidu** [vibhuagrawal14/completing-overlapping-objects#1]
Hello
Can this method output the radius coordinates and the major and minor axes of the ellipse at the same time?

I ran your code and can display the coordinates by clicking on the fitted center point.

Best

**Comment by Aurora-0f** [comment]
> 你好 这个方法可以同时输出椭圆的半径坐标和长短轴吗？
> 
> 我运行了您的代码，可以通过单击拟合的中心点来显示坐标。
> 
> 最好的

Hello, where did you find the picture entered in the code?

**Comment by Aurora-0f** [comment]
> Hello Can this method output the radius coordinates and the major and minor axes of the ellipse at the same time?
> 
> I ran your code and can display the coordinates by clicking on the fitted center point.
> 
> Best

Hello, where did you find the picture entered in the code?

**Comment by laopidu** [comment]
From the internet and paper,some research on segmentation and PSD.

**Comment by Aurora-0f** [comment]
> From the internet and paper,some research on segmentation and PSD.

Do you get a warning like the following?
‘Cannot complete image for radii rMin 10 and rMax 22
due to bad estimation of seed-point for this pair of rMin and rMax’
And how long does it take you to run an image?

**Comment by laopidu** [comment]
yeah i used did

it'll take me about ten seconds,it cost so much time to get a satisfied result.

**Comment by Aurora-0f** [comment]
> yeah i used did
> 
> it'll take me about ten seconds,it cost so much time to get a satisfied result.

I'm sorry, because I haven't read the code carefully, he read in 5 pictures, is there any connection between these 5 pictures?

**Comment by laopidu** [comment]
yes ,the Step1.png is a big part of the final result

**Comment by Aurora-0f** [comment]
> 是的，Step1.png 是最终结果的很大一部分

Is the original image he read in RGB or grayscale?

**Comment by laopidu** [comment]
you can read the whole document
